### ISSUE TITLE
.NET 5 not supported

### ISSUE THREAD

**Issue by mdarocha** [moly/resharper-to-codeclimate#2]
It seems like 1.0.3 does not run under .net 5.

It looks like 87d691af17aaf7e32010297875008e6a68080956 removed the `.net5.0` target.
Can you restore it?

**Comment by moly** [comment]
Hi, please check https://www.nuget.org/packages/resharper-to-codeclimate/1.0.4

**Comment by mdarocha** [comment]
Its fixed, thanks!
